version: '3.8'

services:
  db:
    build: ./pg_docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reviews
    volumes:
      - ./pg_docker/init.csv:/docker-entrypoint-initdb.d/init.csv
      - ./pg_docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"